version: 0.1
phases:
  install:
    commands:
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-cache policy docker-ce
      - apt-get install -y docker-ce
  build:
    commands:
      - env
      - docker build -t "${GIT_USER}:${GIT_PACKAGE}/${GIT_BRANCH}" AmazonLinux
      - docker tag "${GIT_USER}:${GIT_PACKAGE}/${GIT_BRANCH}" "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO}:${GIT_PACKAGE}@${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - docker tag "${GIT_USER}:${GIT_PACKAGE}/${GIT_BRANCH}" "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO}:${GIT_PACKAGE}/${GIT_BRANCH}"
      - docker push "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO}:${GIT_PACKAGE}/${GIT_BRANCH}"
      - touch artifact.txt
artifacts:
  type: zip
  files:
    - artifact.txt
  discard-paths: yes