version: 0.1
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - env
      - pwd
      - bash build.sh
artifacts:
  type: zip
  files:
    - artifact.txt
  discard-paths: yes